name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ 'head', '3.0', '2.7', '2.6' ]
    steps:
    - name: git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global advice.detachedHead 0
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set up Bundler
      run: gem install bundler --no-document
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: rake
    - name: Package
      id: package
      run: rake build
      if: "matrix.ruby == '3.0'"
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        path: pkg
      if: "matrix.ruby == '3.0'"
